server:
  port: 9005
spring:
  application:
    name: service-location-simulator
gpsSimmulator:
  googleApiKey:
  
---
spring:
  profiles: test
ribbon:
  eureka:
    enabled: false
fleet-location-ingest:
  ribbon:
    listOfServers: localhost:9006