server:
  port: 9007
spring:
  cloud:
    stream:
      bindings:
        input: vehicles

---
spring:
  profiles: test
ribbon:
  eureka:
    enabled: false
service-location-service:
  ribbon:
    listOfServers: localhost:9001